### ISSUE TITLE
Questions about applying GLUE on integrating scRNA-seq data and protein data

### ISSUE THREAD

**Issue by HelloWorldLTY** [gao-lab/GLUE#1]
Hi, I wonder if it is possible to apply glue to match gene expression and protein data, but it seems that we do not have chr information this time, so it would be harder for us to construct the prior graph. Is it possible? Thanks.

**Comment by Jeff1995** [comment]
Constructing the prior graph among genes and proteins should also be as easy. You can just connect the proteins and their corresponding genes.

**Comment by subercui** [comment]
Hi, is this the best practice to go if we are working on cite-seq data?

> Constructing the prior graph among genes and proteins should also be as easy. You can just connect the proteins and their corresponding genes.

**Comment by Jeff1995** [comment]
I'd say this is easiest way we can think of, that uses off-the-shelf relations between proteins and genes. Given more information like empirical protein-gene correlation, we might be able to construct more informative guidance graphs, but we have yet to test that.
