### ISSUE TITLE
Question about the knowledge graph

### ISSUE THREAD

**Issue by sinkahak** [gao-lab/GLUE#104]
Hi,

Have you explored the possibility of expanding the knowledge graph to encompass also the connections between TFs and target genes and TFs and their corresponding peaks (motifs)? What prompted the decision to solely incorporate gene-to-peak connections into the graph and derive the remaining connections from that foundation?

Thanks for the reply already in advance!

Best,
Sini

**Comment by Jeff1995** [comment]
Hi @sinkahak. Thanks for your interest in GLUE!

This is a good question. During model development we did plan to add connections between TFs and target genes initially, but later we realized that such within-modality connections would not benefit the integration across modalities, so did not bother adding them in the final model.

Meanwhile, connection between TFs and their corresponding peaks is also cross-modality, and would possibly be helpful. We did not explore this and it would be interesting to see if including such connection would provide further improvements.
