### ISSUE TITLE
Inconsistent File Download for ENCODE TF-human Dataset

### ISSUE THREAD

**Issue by aqlkzf** [gao-lab/GLUE#105]
I am experiencing an issue when attempting to download the 'metadata.tsv' file from the ENCODE project using the provided URL. The download has been inconsistent, yielding different results when using different methods:

- Using `wget`, the result is a file with only one line.
- Using Chrome for download, sometimes the file is also just one line, while at other times, the file size is 141.86MB.
- In all cases, checking the MD5 checksum fails, indicating that the downloaded file does not match the expected checksum (`ba8dce8f6aca4b875bbd08a949ab8dfb`).

**Steps to Reproduce:**
1. Attempt to download the file using `wget` with the following command:
   ```
   wget -O metadata.tsv "https://www.encodeproject.org/metadata/?type=Experiment&control_type%21=%2A&status=released&perturbed=false&assay_title=TF+ChIP-seq&replicates.library.biosample.donor.organism.scientific_name=Mus+Musculus&audit.ERROR.category%21=extremely+low+read+depth&audit.ERROR.category%21=missing+control+alignments&audit.ERROR.category%21=not+compliant+biosample+characterization&audit.ERROR.category%21=missing+compliant+biosample+characterization&audit.ERROR.category%21=control+extremely+low+read+depth&audit.ERROR.category%21=extremely+low+read+length&audit.ERROR.category%21=file+validation_error"
   ```
2. Verify the MD5 checksum of the downloaded file using:
   ```
   md5sum metadata.tsv
   ```
3. Attempt to download the file using Chrome and observe the file size and content.

**Expected Result:**
The file downloaded should match the provided MD5 checksum and have consistent content and size across different download methods.

**Actual Result:**
The downloaded file's content and size are inconsistent, and the MD5 checksum validation fails in all cases.

**Additional Information:**
- Access date of the file: Aug 4, 2022
- Expected MD5SUM: ba8dce8f6aca4b875bbd08a949ab8dfb
- File URL: [ENCODE Project Metadata URL](https://www.encodeproject.org/metadata/?type=Experiment&control_type%21=%2A&status=released&perturbed=false&assay_title=TF+ChIP-seq&replicates.library.biosample.donor.organism.scientific_name=Mus+Musculus&audit.ERROR.category%21=extremely+low+read+depth&audit.ERROR.category%21=missing+control+alignments&audit.ERROR.category%21=not+compliant+biosample+characterization&audit.ERROR.category%21=missing+compliant+biosample+characterization&audit.ERROR.category%21=control+extremely+low+read+depth&audit.ERROR.category%21=extremely+low+read+length&audit.ERROR.category%21=file+validation_error)

I appreciate any assistance or insights into resolving this issue.

**Comment by Jeff1995** [comment]
Hi @aqlkzf. This is likely because the ENCODE data matrix is being dynamically updated. If you are trying to use the TF binding data for your own purposes, using the latest version from ENCODE should be fine (and better actually), but if you are trying to reproduce results in our paper, I'd be glad to upload the metadata file as I obtained it at that time.

**Comment by aqlkzf** [comment]
Thanks for your help.
