### ISSUE TITLE
Can GLUE transfer cell labels from one dataset to another? 

### ISSUE THREAD

**Issue by Telogen** [gao-lab/GLUE#12]
Hi team! I see GLUE  can successfully integrate multiple single-cell datasets cross modalities. I wonder if the cell types of one dataset are known, is it possible to transfer cell labels from one dataset to another? Just like what TransferData() do in Seurat. Many thanks!

**Comment by Jeff1995** [comment]
Absolutely! We have an [`scglue.data.transfer_labels`](https://scglue.readthedocs.io/en/latest/api/scglue.data.transfer_labels.html) function for that purpose.

You need to first populate `obsm` of the datasets with GLUE embeddings, and then use this function to transfer labels.
The code will be something like:

```py
ref.obsm["X_glue"] = glue.encode_data("ref_modality", ref)
query.obsm["X_glue"] = glue.encode_data("query_modality", query)
scglue.data.transfer_labels(ref, query, "cell_type", use_rep="X_glue")
```

**Comment by Telogen** [comment]
Tthanks for your answering!
