### ISSUE TITLE
ValueError in   scglue.models.fit_SCGLUE

### ISSUE THREAD

**Issue by jisnoalia** [gao-lab/GLUE#13]
Hi,when i run the **scglue.models.fit_SCGLUE**,
`glue = scglue.models.fit_SCGLUE(
    {"rna": rna, "atac": atac}, graph,
    fit_kws={"directory": "glue"}
)`

my RNA  and  ATAC are  transferred from Seurat.
it shows this error :

[INFO] fit_SCGLUE: Pretraining SCGLUE model...
[WARNING] SCGLUEModel: It is recommended that `use_rep` dimensionality be equal or larger than `latent_dim`.
[INFO] autodevice: Using GPU 0 as computation device.
[INFO] SCGLUEModel: Setting `graph_batch_size` = 11613
[INFO] SCGLUEModel: Setting `max_epochs` = 48
[INFO] SCGLUEModel: Setting `patience` = 4
[INFO] SCGLUEModel: Setting `reduce_lr_patience` = 2
[INFO] SCGLUETrainer: Using training directory: "glue/pretrain"
Current run is terminating due to exception: Expected value argument (Tensor of shape (128, 2000)) to be within the support (IntegerGreaterThan(lower_bound=0)) of the distribution NegativeBinomial(total_count: torch.Size([128, 2000]), logits: torch.Size([128, 2000])), but found invalid values:
tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 2.2001, 0.0000, 0.0000],
        [1.0265, 0.0000, 0.0000,  ..., 2.0998, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 2.1896, 0.0000, 0.2278]],
       device='cuda:0')
Engine run is terminating due to exception: Expected value argument (Tensor of shape (128, 2000)) to be within the support (IntegerGreaterThan(lower_bound=0)) of the distribution NegativeBinomial(total_count: torch.Size([128, 2000]), logits: torch.Size([128, 2000])), but found invalid values:
tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 2.2001, 0.0000, 0.0000],
        [1.0265, 0.0000, 0.0000,  ..., 2.0998, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 2.1896, 0.0000, 0.2278]],
       device='cuda:0')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [58], in <cell line: 1>()
----> 1 glue = scglue.models.fit_SCGLUE(
      2     {"rna": rna, "atac": atac}, graph,
      3     fit_kws={"directory": "glue"}
      4 )

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/scglue/models/__init__.py:91, in fit_SCGLUE(adatas, graph, model, init_kws, compile_kws, fit_kws, balance_kws)
     89 pretrain = model(adatas, sorted(graph.nodes), **pretrain_init_kws)
     90 pretrain.compile(**compile_kws)
---> 91 pretrain.fit(adatas, graph, **pretrain_fit_kws)
     92 if "directory" in pretrain_fit_kws:
     93     pretrain.save(os.path.join(pretrain_fit_kws["directory"], "pretrain.dill"))

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/scglue/models/scglue.py:1511, in SCGLUEModel.fit(self, adatas, graph, edge_weight, edge_sign, neg_samples, val_split, data_batch_size, graph_batch_size, align_burnin, safe_burnin, max_epochs, patience, reduce_lr_patience, wait_n_lrs, directory)
   1508 if self.trainer.freeze_u:
   1509     self.logger.info("Cell embeddings are frozen")
-> 1511 super().fit(
   1512     data, graph, val_split=val_split,
   1513     data_batch_size=data_batch_size, graph_batch_size=graph_batch_size,
   1514     align_burnin=align_burnin, safe_burnin=safe_burnin,
   1515     max_epochs=max_epochs, patience=patience,
   1516     reduce_lr_patience=reduce_lr_patience, wait_n_lrs=wait_n_lrs,
   1517     random_seed=self.random_seed,
   1518     directory=directory
   1519 )

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/scglue/models/base.py:334, in Model.fit(self, *args, **kwargs)
    319 def fit(self, *args, **kwargs) -> None:
    320     r"""
    321     Alias of ``.trainer.fit``.
    322 
   (...)
    332     Subclasses may override arguments for API definition.
    333     """
--> 334     self.trainer.fit(*args, **kwargs)

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/scglue/models/glue.py:608, in GLUETrainer.fit(self, data, graph, val_split, data_batch_size, graph_batch_size, align_burnin, safe_burnin, max_epochs, patience, reduce_lr_patience, wait_n_lrs, random_seed, directory, plugins)
    606 plugins = default_plugins + (plugins or [])
    607 try:
--> 608     super().fit(
    609         train_loader, val_loader=val_loader,
    610         max_epochs=max_epochs, random_seed=random_seed,
    611         directory=directory, plugins=plugins
    612     )
    613 finally:
    614     data.clean()

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/scglue/models/base.py:200, in Trainer.fit(self, train_loader, val_loader, max_epochs, random_seed, directory, plugins)
    198 # Start engines
    199 torch.manual_seed(random_seed)
--> 200 train_engine.run(train_loader, max_epochs=max_epochs)
    202 torch.cuda.empty_cache()

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/ignite/engine/engine.py:704, in Engine.run(self, data, max_epochs, epoch_length, seed)
    701         raise ValueError("epoch_length should be provided if data is None")
    703 self.state.dataloader = data
--> 704 return self._internal_run()

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/ignite/engine/engine.py:783, in Engine._internal_run(self)
    781     self._dataloader_iter = None
    782     self.logger.error(f"Engine run is terminating due to exception: {e}")
--> 783     self._handle_exception(e)
    785 self._dataloader_iter = None
    786 return self.state

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/ignite/engine/engine.py:464, in Engine._handle_exception(self, e)
    462 def _handle_exception(self, e: BaseException) -> None:
    463     if Events.EXCEPTION_RAISED in self._event_handlers:
--> 464         self._fire_event(Events.EXCEPTION_RAISED, e)
    465     else:
    466         raise e

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/ignite/engine/engine.py:421, in Engine._fire_event(self, event_name, *event_args, **event_kwargs)
    419 kwargs.update(event_kwargs)
    420 first, others = ((args[0],), args[1:]) if (args and args[0] == self) else ((), args)
--> 421 func(*first, *(event_args + others), **kwargs)

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/scglue/models/base.py:163, in Trainer.fit.<locals>._handle_exception(engine, e)
    161     engine.terminate()
    162 else:
--> 163     raise e

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/ignite/engine/engine.py:753, in Engine._internal_run(self)
    750 if self._dataloader_iter is None:
    751     self._setup_engine()
--> 753 time_taken = self._run_once_on_dataset()
    754 # time is available for handlers but must be update after fire
    755 self.state.times[Events.EPOCH_COMPLETED.name] = time_taken

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/ignite/engine/engine.py:854, in Engine._run_once_on_dataset(self)
    852 except Exception as e:
    853     self.logger.error(f"Current run is terminating due to exception: {e}")
--> 854     self._handle_exception(e)
    856 return time.time() - start_time

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/ignite/engine/engine.py:464, in Engine._handle_exception(self, e)
    462 def _handle_exception(self, e: BaseException) -> None:
    463     if Events.EXCEPTION_RAISED in self._event_handlers:
--> 464         self._fire_event(Events.EXCEPTION_RAISED, e)
    465     else:
    466         raise e

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/ignite/engine/engine.py:421, in Engine._fire_event(self, event_name, *event_args, **event_kwargs)
    419 kwargs.update(event_kwargs)
    420 first, others = ((args[0],), args[1:]) if (args and args[0] == self) else ((), args)
--> 421 func(*first, *(event_args + others), **kwargs)

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/scglue/models/base.py:163, in Trainer.fit.<locals>._handle_exception(engine, e)
    161     engine.terminate()
    162 else:
--> 163     raise e

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/ignite/engine/engine.py:840, in Engine._run_once_on_dataset(self)
    838 self.state.iteration += 1
    839 self._fire_event(Events.ITERATION_STARTED)
--> 840 self.state.output = self._process_function(self, self.state.batch)
    841 self._fire_event(Events.ITERATION_COMPLETED)
    843 if self.should_terminate or self.should_terminate_single_epoch:

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/scglue/models/scglue.py:728, in SCGLUETrainer.train_step(self, engine, data)
    725     self.dsc_optim.step()
    727 # Generator step
--> 728 losses = self.compute_losses(data, epoch)
    729 self.net.zero_grad(set_to_none=True)
    730 losses["gen_loss"].backward()

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/scglue/models/scglue.py:674, in SCGLUETrainer.compute_losses(self, data, epoch, dsc_only)
    671 g_kl = D.kl_divergence(v, prior).sum(dim=1).mean() / vsamp.shape[0]
    672 g_elbo = g_nll + self.lam_kl * g_kl
--> 674 x_nll = {
    675     k: -net.u2x[k](
    676         usamp[k], vsamp[getattr(net, f"{k}_idx")], xbch[k], l[k]
    677     ).log_prob(x[k]).mean()
    678     for k in net.keys
    679 }
    680 x_kl = {
    681     k: D.kl_divergence(
    682         u[k], prior
    683     ).sum(dim=1).mean() / x[k].shape[1]
    684     for k in net.keys
    685 }
    686 x_elbo = {
    687     k: x_nll[k] + self.lam_kl * x_kl[k]
    688     for k in net.keys
    689 }

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/scglue/models/scglue.py:675, in <dictcomp>(.0)
    671 g_kl = D.kl_divergence(v, prior).sum(dim=1).mean() / vsamp.shape[0]
    672 g_elbo = g_nll + self.lam_kl * g_kl
    674 x_nll = {
--> 675     k: -net.u2x[k](
    676         usamp[k], vsamp[getattr(net, f"{k}_idx")], xbch[k], l[k]
    677     ).log_prob(x[k]).mean()
    678     for k in net.keys
    679 }
    680 x_kl = {
    681     k: D.kl_divergence(
    682         u[k], prior
    683     ).sum(dim=1).mean() / x[k].shape[1]
    684     for k in net.keys
    685 }
    686 x_elbo = {
    687     k: x_nll[k] + self.lam_kl * x_kl[k]
    688     for k in net.keys
    689 }

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/torch/distributions/negative_binomial.py:92, in NegativeBinomial.log_prob(self, value)
     90 def log_prob(self, value):
     91     if self._validate_args:
---> 92         self._validate_sample(value)
     94     log_unnormalized_prob = (self.total_count * F.logsigmoid(-self.logits) +
     95                              value * F.logsigmoid(self.logits))
     97     log_normalization = (-torch.lgamma(self.total_count + value) + torch.lgamma(1. + value) +
     98                          torch.lgamma(self.total_count))

File ~/miniconda3/envs/glue/lib/python3.9/site-packages/torch/distributions/distribution.py:288, in Distribution._validate_sample(self, value)
    286 valid = support.check(value)
    287 if not valid.all():
--> 288     raise ValueError(
    289         "Expected value argument "
    290         f"({type(value).__name__} of shape {tuple(value.shape)}) "
    291         f"to be within the support ({repr(support)}) "
    292         f"of the distribution {repr(self)}, "
    293         f"but found invalid values:\n{value}"
    294     )

ValueError: Expected value argument (Tensor of shape (128, 2000)) to be within the support (IntegerGreaterThan(lower_bound=0)) of the distribution NegativeBinomial(total_count: torch.Size([128, 2000]), logits: torch.Size([128, 2000])), but found invalid values:
tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 2.2001, 0.0000, 0.0000],
        [1.0265, 0.0000, 0.0000,  ..., 2.0998, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 2.1896, 0.0000, 0.2278]],
       device='cuda:0')

**Comment by Jeff1995** [comment]
Thanks for your interest in GLUE! You are seeing this error because the data provided are not raw counts.

By default the model uses the `.X` slot of the data objects. You can also specify a layer via `use_layer` in [`scglue.models.configure_dataset`](https://scglue.readthedocs.io/en/latest/api/scglue.models.scglue.configure_dataset.html). Whichever way is okay, but you have to make sure the RNA and ATAC data being used are both raw counts.

**Comment by jisnoalia** [comment]
Thanks! I might slove this problem through select raw counts.
