### ISSUE TITLE
can Glue make GRN

### ISSUE THREAD

**Issue by dandata123-tech** [gao-lab/GLUE#15]
Hi,your work about GLUE is very good,but i have a few question.
Your article mentioned that with the use of omic data ,we can build GRN through our method.But i can not find the code.
Will you be so kind to provide the code with me?
Yours,
Dan

**Comment by Jeff1995** [comment]
The GRN-building script we used in the manuscript can be found [here](https://github.com/gao-lab/GLUE/blob/master/experiments/RegInf/s04_infer_gene_tf.py).

Nevertheless, the script contains code for benchmarking purposes which is unnecessary for end users. We are actively working on a dedicated GRN-building tutorial which will be much easier to follow. I'll let you know when that's ready!

**Comment by dandata123-tech** [comment]
Thanks a lot,looking for your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gao-lab/GLUE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月15日(星期天) 中午11:50
***@***.***&gt;;
抄送:&nbsp;"Dan ***@***.******@***.***&gt;;
主题:&nbsp;Re: [gao-lab/GLUE] can Glue make GRN (Issue #15)





 
The GRN-building script we used in the manuscript can be found here.
 
Nevertheless, the script contains code for benchmarking purposes which is unnecessary for end users. We are actively working on a dedicated GRN-building tutorial which will be much easier to follow. I'll let you know when that's ready!

**Comment by Jeff1995** [comment]
Sorry for the delay! The regulatory inference tutorial is now available at https://scglue.readthedocs.io/en/latest/reginf.html.
