### ISSUE TITLE
The download website cann't use

### ISSUE THREAD

**Issue by liukeweiaway** [gao-lab/GLUE#16]
https://www.dropbox.com/s/dl/kqsy9tvsklbu7c4/allen_brain.rds  cann't use in 'GLUE/data/download/10x-ATAC-Brain5k'

**Comment by liukeweiaway** [comment]
good work

**Comment by Jeff1995** [comment]
Sorry for the inconvenience! You may download the file from here:

ftp://ftp.cbi.pku.edu.cn/pub/glue-download/allen_brain.rds
