### ISSUE TITLE
关于GLUE在大型数据集上所需的服务器配置

### ISSUE THREAD

**Issue by MMCXXVI** [gao-lab/GLUE#18]
高歌教授、曹志杰博士您好，十分感谢你们在15号晚上关于GLUE的研究分享，你们在里面提出了GLUE首次实现了百万级别单细胞数据的整合，那么使用GLUE进行百万级别单细胞数据的整合分析时，服务器需达到什么规模的计算资源呢（例如内存大小）？以及是否支持服务器集群的并行运算？能否分享一下你们在文中提出整合”人类胎儿全器官单细胞转录组和染色质开放组图谱“这个数据时所占用的服务器资源配置吗？
期待你们的回复，谢谢！

**Comment by Jeff1995** [comment]
Thanks for your interest in GLUE!

Running GLUE integration itself took 20 CPU cores, ~100GB RAM and a single 2080Ti GPU (using ~6GB VRAM),
but the preprocessing step took ~200GB RAM.

The number of CPU cores should be flexible, but RAM and VRAM requirements have to be met.

GLUE currently does not support parallel computing across multiple nodes, so the resources need to be allocated with a single node.

**Comment by MMCXXVI** [comment]
您发给我的邮件已经收到。--------------------------------------------This is an automatic reply, confirming that your e-mail was received.Thank you
