### ISSUE TITLE
The problem in scglue.data.get_gene_annotation

### ISSUE THREAD

**Issue by jisnoalia** [gao-lab/GLUE#19]
When I run scglue.data.get_gene_annotation  to obtain genomic coordinates, occurs this problem.
https://raw.githubusercontent.com/jisnoalia/image/master/img/202205201031888.png
~~~~python
len( list(rna.var[~rna.var.isna().any(axis=1)].index))
6236
len( list(rna.var[rna.var.isna().any(axis=1)].index))
20351
~~~~

https://raw.githubusercontent.com/jisnoalia/image/master/img/202205201039666.png

But I can find the gene like FAM87B in gtf file.I don't know if this problem affects the analysis.

**Comment by Jeff1995** [comment]
What `gtf_by` did you use? Does the `gtf_by` attribute in the GTF file match exactly with the var names?

**Comment by jisnoalia** [comment]
I use the gene_name as the `gtf_by`.when I can grep the gene_name in gtf at the shell.
![image-20220523084535510](https://raw.githubusercontent.com/jisnoalia/image/master/img/202205230845613.png)


![image-20220523084655362](https://raw.githubusercontent.com/jisnoalia/image/master/img/202205230846430.png)

**Comment by Jeff1995** [comment]
Well that's strange... Could you please provide a minimal `h5ad` file (you can subsample your data to retain just a couple of cells) and a GTF file that produces the error, so I can take a closer look?

**Comment by jisnoalia** [comment]
I extracted &nbsp;informations manually from the gtf file in bash, replaced the rna.var.&nbsp;How do i send the file to you？

发自我的iPhone


------------------ Original ------------------
From: Zhi-Jie Cao ***@***.***&gt;
Date: Mon,May 23,2022 11:44 PM
To: gao-lab/GLUE ***@***.***&gt;
Cc: jisnoalia ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [gao-lab/GLUE] The problem in scglue.data.get_gene_annotation (Issue #19)






Well that's strange... Could you please provide a minimal h5ad file (you can subsample your data to retain just a couple of cells) and a GTF file that produces the error, so I can take a closer look?

**Comment by Jeff1995** [comment]
Okay. You may share the files via Google drive or similar storage services.
