### ISSUE TITLE
feature selection

### ISSUE THREAD

**Issue by Hongru-Hu** [gao-lab/GLUE#2]
Hi, I looked at the recoding of your open problem presentation and I was wondering 1) if there's a careful feature selection for either the ATACseq data and the RNAseq data? 20 how many scATACseq peaks and scRNAseq genes you selected for the model training? Thanks!

**Comment by Jeff1995** [comment]
Hi Hongru! Thanks for your interest.

1. Feature selection was performed using scanpy function [sc.pl.highly_variable_genes](https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.highly_variable_genes.html). Batch key was set as a light-weight batch correction.
2. We optimized the number of highly variable genes as a hyperparameter. The optimal values were 5,000 genes for CITE and 10,000 genes for Multiome.

**Comment by Hongru-Hu** [comment]
Thanks @Jeff1995, I was wondering how the differentially accessible peaks got selected? (based on some threshold settings for "rare" or "common" peaks?) thanks again!

**Comment by Jeff1995** [comment]
Oh sorry I missed the ATAC part...

We used 30,000 peaks that are detected in the most cells (most "common" peaks). But in the ATAC case we found that the number of selected peaks had a much smaller impact on performance, compared to the number of selected genes in GEX.

**Comment by Hongru-Hu** [comment]
Thank you for your clarification. By the way, when using the ATACseq data, were you basically using the binarized peak counts or applying some normalization? Thanks again!

**Comment by Jeff1995** [comment]
The ATAC decoders were trained on raw counts. The ATAC encoders used LSI of raw counts.

**Comment by xuerchen** [comment]
Hello, I'd like to learn more about your winning solution `CLUE` in modality matching. It seems only a wheel file is available at the moment. When can I expect the release of the source code of CLUE? Thank you so much.

**Comment by xuerchen** [comment]
Another question is do you observe significant improvement from vanilla auto encoder to the variational auto encoder? Thank you!

**Comment by Jeff1995** [comment]
> Hello, I'd like to learn more about your winning solution `CLUE` in modality matching. It seems only a wheel file is available at the moment. When can I expect the release of the source code of CLUE? Thank you so much.

Sorry for the late response! The `CLUE` code is now available in the latest [v0.2.0 release](https://github.com/gao-lab/GLUE/releases/tag/v0.2.0).

> Another question is do you observe significant improvement from vanilla auto encoder to the variational auto encoder? Thank you!

We did not try vanilla autoencoders, but there is a `lam_kl` parameter in the current implementation controlling weight of the KL term in VAE. I think setting it to 0 is equivalent to a vanilla autoencoder. For CLUE in the competition we did a hyperparameter search, and the optimal `lam_kl` were not very far away from 1.0 (`lam_kl = 1.0` for CITE and `lam_kl = 0.3` for Multiome. You can find these parameters [here](https://github.com/openproblems-bio/neurips2021_multimodal_topmethods/blob/7dc3b2896ca843f973fe6685d8df7fc9630a9229/src/match_modality/methods/clue/train/script.py#L52)).
