### ISSUE TITLE
The combined don't have var.

### ISSUE THREAD

**Issue by jisnoalia** [gao-lab/GLUE#20]
when I run Like the following，
~~~~python
glue = scglue.models.fit_SCGLUE(
    {"rna": rna, "atac": atac}, graph,
    fit_kws={"directory": "glue2"}
)
dx = scglue.models.integration_consistency(
    glue, {"rna": rna, "atac": atac}, graph,
    count_layers={"rna": "counts","atac": "counts"}
)
dx
_ = sns.lineplot(x="n_meta", y="consistency", data=dx).axhline(y=0.05, c="darkred", ls="--")
rna.obsm["X_glue"] = glue.encode_data("rna", rna)
atac.obsm["X_glue"] = glue.encode_data("atac", atac)
combined = anndata.concat([rna, atac])
~~~~
I get this combined.
AnnData object with n_obs × n_vars = 592831 × 0
    obs: 'sample', 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'patient', 'tissue', 'balancing_weight'
    uns: 'neighbors', 'umap'
    obsm: 'X_umap', 'X_glue'
    layers: 'counts'
    obsp: 'distances', 'connectivities'

I can't understand it !!!!

**Comment by Jeff1995** [comment]
Thanks for your interest in GLUE!

The integration result of GLUE is stored as a set of cell embeddings in `combined.obsm["X_glue"]`.

The feature set in `combined` is empty because [`anndata.concat`](https://anndata.readthedocs.io/en/latest/generated/anndata.concat.html) takes an "inner" join by default, and their is no common feature between RNA and ATAC.

**Comment by jisnoalia** [comment]
I check the sample data in tutorials. Do you mean to must have a feature like `cell_type` between RNA and ATAC?

**Comment by Jeff1995** [comment]
No. In short, the result you see is normal:

```
AnnData object with n_obs × n_vars = 592831 × 0
obs: 'sample', 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'patient', 'tissue', 'balancing_weight'
uns: 'neighbors', 'umap'
obsm: 'X_umap', 'X_glue'
layers: 'counts'
obsp: 'distances', 'connectivities'
```

The integration result is stored in `combined.obsm["X_glue"]`.

E.g., you can continue to make UMAP plots using this `combined` object:

```
sc.pp.neighbors(combined, use_rep="X_glue", metric="cosine")
sc.tl.umap(combined)
sc.pl.umap(combined, color="orig.ident")  # Assuming you want to visualize "orig.ident" on the UMAP plot
```

`combined.X` is not used, so an empty `combined.X` doesn't matter.
