### ISSUE TITLE
Error on scglue.genomics.rna_anchored_prior_graph

### ISSUE THREAD

**Issue by cissizhang** [gao-lab/GLUE#22]
Hi,  I have the error when running  scglue.genomics.rna_anchored_prior_graph(rna, atac) when using the data provided in the tutorial. The error stated the bedtools version should be >=2.29.2, however, the bedtools is 2.30.0. I even reinstalled everything. Unfortuenly, the error didn't disappear. I would be appreciate if you can help me to figure it out.  Thanks!
![error-screen-shot](https://user-images.githubusercontent.com/106272277/170337601-500e413a-f955-42ce-b32f-7e26cb661842.png)
![tool-version](https://user-images.githubusercontent.com/106272277/170337637-0b7a0135-9ef3-4760-8c42-203b2c284851.png)
!

**Comment by Jeff1995** [comment]
Error code 127 means the command cannot be found or is not executable.

Could you please run `bedtools --version` to verify that the bedtools executable can indeed be found? If not, you may try deactivating and reactivating the conda environment and see if the error goes away?

**Comment by cissizhang** [comment]
Hi, Thanks for the quick reply. Actually, I figured out the error is caused by bedtools path in my jupyterhub environment. I have to use the "absolute path" of bedtools, otherwise the code can't find it. So my question is if it is possible to add the path of bedtools to the code. Thank you.

**Comment by Jeff1995** [comment]
Thanks for the clarification. The current version does not support that, but I can add it in the best release. I will let you know when that's ready. In the meantime, you may also ask your Jupyter hub admin and see if there is a solution on the environment side?

**Comment by Telogen** [comment]
Hi developer, I also  met some srrors when I run `scglue.genomics.rna_anchored_prior_graph()`, following are the tracebacks:
```
IntCastingNaNError                        Traceback (most recent call last)
Input In [18], in <module>
----> 1 graph = scglue.genomics.rna_anchored_prior_graph(rna, atac)
      2 graph

File ~/anaconda3/envs/singlecell/lib/python3.8/site-packages/scglue/genomics.py:523, in rna_anchored_prior_graph(rna, gene_region, promoter_len, extend_range, extend_fn, signs, propagate_highly_variable, corrupt_rate, random_state, *others)
    520 if set(signs).difference({-1, 1}):
    521     raise RuntimeError("``signs`` can only contain {-1, 1}!")
--> 523 rna_bed = Bed(rna.var.assign(name=rna.var_names))
    524 other_beds = [Bed(other.var.assign(name=other.var_names)) for other in others]
    525 if gene_region == "promoter":

File ~/anaconda3/envs/singlecell/lib/python3.8/site-packages/scglue/utils.py:478, in ConstrainedDataFrame.__init__(self, *args, **kwargs)
    476 def __init__(self, *args, **kwargs) -> None:
    477     df = pd.DataFrame(*args, **kwargs)
--> 478     df = self.rectify(df)
    479     self.verify(df)
    480     super().__init__(df)

File ~/anaconda3/envs/singlecell/lib/python3.8/site-packages/scglue/genomics.py:47, in Bed.rectify(cls, df)
     45 if item in df:
     46     if item in ("chromStart", "chromEnd"):
---> 47         df[item] = df[item].astype(int)
     48     else:
     49         df[item] = df[item].astype(str)

File ~/anaconda3/envs/singlecell/lib/python3.8/site-packages/pandas/core/generic.py:5920, in NDFrame.astype(self, dtype, copy, errors)
   5913     results = [
   5914         self.iloc[:, i].astype(dtype, copy=copy)
   5915         for i in range(len(self.columns))
   5916     ]
   5918 else:
   5919     # else, only a single dtype is given
-> 5920     new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
   5921     return self._constructor(new_data).__finalize__(self, method="astype")
   5923 # GH 33113: handle empty frame or series

File ~/anaconda3/envs/singlecell/lib/python3.8/site-packages/pandas/core/internals/managers.py:419, in BaseBlockManager.astype(self, dtype, copy, errors)
    418 def astype(self: T, dtype, copy: bool = False, errors: str = "raise") -> T:
--> 419     return self.apply("astype", dtype=dtype, copy=copy, errors=errors)

File ~/anaconda3/envs/singlecell/lib/python3.8/site-packages/pandas/core/internals/managers.py:304, in BaseBlockManager.apply(self, f, align_keys, ignore_failures, **kwargs)
    302         applied = b.apply(f, **kwargs)
    303     else:
--> 304         applied = getattr(b, f)(**kwargs)
    305 except (TypeError, NotImplementedError):
    306     if not ignore_failures:

File ~/anaconda3/envs/singlecell/lib/python3.8/site-packages/pandas/core/internals/blocks.py:580, in Block.astype(self, dtype, copy, errors)
    562 """
    563 Coerce to the new dtype.
    564 
   (...)
    576 Block
    577 """
    578 values = self.values
--> 580 new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
    582 new_values = maybe_coerce_values(new_values)
    583 newb = self.make_block(new_values)

File ~/anaconda3/envs/singlecell/lib/python3.8/site-packages/pandas/core/dtypes/cast.py:1292, in astype_array_safe(values, dtype, copy, errors)
   1289     dtype = dtype.numpy_dtype
   1291 try:
-> 1292     new_values = astype_array(values, dtype, copy=copy)
   1293 except (ValueError, TypeError):
   1294     # e.g. astype_nansafe can fail on object-dtype of strings
   1295     #  trying to convert to float
   1296     if errors == "ignore":

File ~/anaconda3/envs/singlecell/lib/python3.8/site-packages/pandas/core/dtypes/cast.py:1237, in astype_array(values, dtype, copy)
   1234     values = values.astype(dtype, copy=copy)
   1236 else:
-> 1237     values = astype_nansafe(values, dtype, copy=copy)
   1239 # in pandas we don't store numpy str dtypes, so convert to object
   1240 if isinstance(dtype, np.dtype) and issubclass(values.dtype.type, str):

File ~/anaconda3/envs/singlecell/lib/python3.8/site-packages/pandas/core/dtypes/cast.py:1148, in astype_nansafe(arr, dtype, copy, skipna)
   1145     raise TypeError(f"cannot astype a timedelta from [{arr.dtype}] to [{dtype}]")
   1147 elif np.issubdtype(arr.dtype, np.floating) and np.issubdtype(dtype, np.integer):
-> 1148     return astype_float_to_int_nansafe(arr, dtype, copy)
   1150 elif is_object_dtype(arr.dtype):
   1151 
   1152     # work around NumPy brokenness, #1987
   1153     if np.issubdtype(dtype.type, np.integer):

File ~/anaconda3/envs/singlecell/lib/python3.8/site-packages/pandas/core/dtypes/cast.py:1193, in astype_float_to_int_nansafe(values, dtype, copy)
   1189 """
   1190 astype with a check preventing converting NaN to an meaningless integer value.
   1191 """
   1192 if not np.isfinite(values).all():
-> 1193     raise IntCastingNaNError(
   1194         "Cannot convert non-finite values (NA or inf) to integer"
   1195     )
   1196 return values.astype(dtype, copy=copy)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
```

**Comment by HelloWorldLTY** [comment]
> Hi, Thanks for the quick reply. Actually, I figured out the error is caused by bedtools path in my jupyterhub environment. I have to use the "absolute path" of bedtools, otherwise the code can't find it. So my question is if it is possible to add the path of bedtools to the code. Thank you.

Hi, could you please tell me how to add the absolute path of bedtools to this code? I use sys.path.append but it still cannot work. Thanks a lot!

**Comment by cissizhang** [comment]
> 

You have to ask your admin to install the **bedtools** under /usr/local/bin/ or whatever path you can directly called. This is caused by **pybedtools** (https://daler.github.io/pybedtools/main.html). This is how I solved the problem finally.
![bedtools](https://user-images.githubusercontent.com/106272277/173665653-782089df-95d8-4910-9dca-4f14620a03ec.png)

**Comment by Jeff1995** [comment]
Please note that in the latest [v0.2.3](https://github.com/gao-lab/GLUE/releases/tag/v0.2.3), you can now set a custom bedtools path via something like:

```python
scglue.config.BEDTOOLS_PATH = "/path/to/bedtools"
```

**Comment by HelloWorldLTY** [comment]
Great, it works. Many thanks for your help!
![image](https://user-images.githubusercontent.com/43333475/174927945-387b057d-aebc-4095-9ec1-c682054f5e39.png)

**Comment by Saton-anger** [comment]
> Great, it works. Many thanks for your help! ![image](https://user-images.githubusercontent.com/43333475/174927945-387b057d-aebc-4095-9ec1-c682054f5e39.png)

Hey, I have faced the same problems with you, could you please tell me how did you add the custom path of bedtools using `scglue.config.BEDTOOLS_PATH =` ?

**Comment by Paul-YPH** [comment]
I have been troubled by the inability to run the bedtools step for a long time. I have tried various methods, including the methods mentioned above, and even `scglue.config.BEDTOOLS_PATH`, but none of them worked. What's even more weird is that I can run the process directly in **jupyter**, but I still get errors running the **.py** file and my own encapsulated functions.
In the end, my solution was to specify the path directly in the **.py** file using `os`:
```
import os
os.environ['PATH'] += "/path_to_envs/glue/bin"
```
