### ISSUE TITLE
the question about the scglue.data.transfer_labels?

### ISSUE THREAD

**Issue by jisnoalia** [gao-lab/GLUE#23]
I use the `scglue.data.transfer_labels` to transfer the labels from RNA to atac. Does scglue have similar functions to get the  `predicted.labels` that are used in singac to Evaluate the prediction and Confidence score of ATAC cells?  Will scglue retain all cells in ATAC?

**Comment by Jeff1995** [comment]
I'm afraid the `scglue.data.transfer_labels` currently has limited functionality. No confidence score is given and all cells are retained without similarity cutoffs. I agree that these functionalities are nice to have, and will try to add them in future releases. I'll let you know when that's ready.

**Comment by jisnoalia** [comment]
Thank you very much for your reply. I'm looking forward to this function coming out.

发自我的iPhone


------------------ Original ------------------
From: Zhi-Jie Cao ***@***.***&gt;
Date: Sun,May 29,2022 1:21 AM
To: gao-lab/GLUE ***@***.***&gt;
Cc: jisnoalia ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [gao-lab/GLUE] the question about thescglue.data.transfer_labels? (Issue #23)





 
I'm afraid the scglue.data.transfer_labels currently has limited functionality. No confidence score is given and all cells are retained without similarity cutoffs. I agree that these functionalities are nice to have, and will try to add them in future releases. I'll let you know when that's ready.

**Comment by Jeff1995** [comment]
An estimation of transfer confidence is now available in [v0.2.3](https://github.com/gao-lab/GLUE/releases/tag/v0.2.3). Please see the [documentation ("Note" section)](https://scglue.readthedocs.io/en/latest/api/scglue.data.transfer_labels.html) for a brief explanation on how the confidence score is computed.

**Comment by jisnoalia** [comment]
> An estimation of transfer confidence is now available in [v0.2.3](https://github.com/gao-lab/GLUE/releases/tag/v0.2.3). Please see the [documentation ("Note" section)](https://scglue.readthedocs.io/en/latest/api/scglue.data.transfer_labels.html) for a brief explanation on how the confidence score is computed.


Wow！！！  I will try it later. Thank you for this update! It's very helpful for me.
