### ISSUE TITLE
Tutorial for Paired RNA+ATAC dataset

### ISSUE THREAD

**Issue by adamtongji** [gao-lab/GLUE#24]
Hi, thank you for your excellent tools! 
Recently, our collaborator generated a series of 10X multiome datasets, and we hope to use GLUE to our paired datasets.

I found the class `PairedSCGLUEModel` in your "readthedocs" tutorial. Is there a tutorial for this class and applying GLUE to paired-datasets? 

Thanks!

**Comment by Jeff1995** [comment]
Thanks for your interest in GLUE! Currently there is no tutorial for `PairedSCGLUEModel` yet. I will add one and let you know when it's ready.

**Comment by Jeff1995** [comment]
Hi there! The [tutorial](https://scglue.readthedocs.io/en/latest/paired.html) is finally available. Please be advised that you need the latest version (v0.3.2) of scglue to use it.
