### ISSUE TITLE
Tutorial data is not downloadable

### ISSUE THREAD

**Issue by sohrabsa** [gao-lab/GLUE#26]
Hi, I'm going through the tutorial. The h5ad files used in the dataset cannot be downloaded, they require a password, e.g., [ftp://ftp.cbi.pku.edu.cn/pub/glue-download/Chen-2019-RNA.h5ad](ftp://ftp.cbi.pku.edu.cn/pub/glue-download/Chen-2019-RNA.h5ad). 
I was wondering if you could point me to a downloadable h5ad file please.

**Comment by sohrabsa** [comment]
Just to add that when I try to create this file using the scripts provided in the `data` directory, I get the following error:
```FileNotFoundError: [Errno 2] No such file or directory: '../download/Chen-2019/AdBrainCortex_SNAREseq_metadata.csv'```

This points to the only file without a downloadable link in the Chen-2019 dataset:
`https://github.com/gao-lab/GLUE/tree/master/data/download/Chen-2019`

**Comment by HelloWorldLTY** [comment]
I used this code to download: 
wget ftp://ftp.cbi.pku.edu.cn/pub/glue-download/Chen-2019-RNA.h5ad
or you can copy this link to some download software (like bitcomet)
Hope it can help u.

**Comment by sohrabsa** [comment]
Thanks @HelloWorldLTY - I am familiar with the ftp protocol; the issue is that it appears to be restricted access. Have you been able to download this specific file in the past couple of days?

**Comment by Jeff1995** [comment]
Thanks for the report! Maybe it was due to network abnormalities during the last couple of days. I just verified that the link is working. Could you try again with `wget ftp://ftp.cbi.pku.edu.cn/pub/glue-download/Chen-2019-RNA.h5ad`?

**Comment by sohrabsa** [comment]
Thank you. I confirm that the paths work for me.

**Comment by Jeff1995** [comment]
Sorry I just realized that the *tutorial datasets* are a bit different from those on the download page. For the *tutorial datasets*, some meta information like genomic coordinates were stripped on purpose so it's easier to demonstrate how to populate them for new datasets.

I just uploaded these *tutorial datasets* to `download.gao-lab.org` as well. If you're trying to follow the tutorials, please use the following links:

* [http://download.gao-lab.org/GLUE/tutorial/Chen-2019-RNA.h5ad](http://download.gao-lab.org/GLUE/tutorial/Chen-2019-RNA.h5ad)
* [http://download.gao-lab.org/GLUE/tutorial/Chen-2019-ATAC.h5ad](http://download.gao-lab.org/GLUE/tutorial/Chen-2019-ATAC.h5ad)
