### ISSUE TITLE
Batch Effect Mechanism

### ISSUE THREAD

**Issue by ilan-gold** [gao-lab/GLUE#28]
Hi,

Thanks for the `register` function - works great!

I'm wondering why the batch effect mechanism requires that the datasets have identical batches - are batches passed in during training during the training i.e only one batch used for every mini-batch?  Is there a reason for this?

**Comment by Jeff1995** [comment]
Sorry for the late response! Could you clarify which part of the code implies one batch is used for every mini-batch? I think the current implementation does allow multiple batches in each mini-batch, and different datasets can have different batches.

**Comment by ilan-gold** [comment]
Perhaps I was unclear in my question - I meant that the batches between modalities must match exactly.  So if I have ATAC and RNA data, they must have identical batch labels.  So if I have three patients, A, B, and C, for example, from whom ATAC and RNA seq were performed, the data needs to have come from the same one, two or three patients.  But it doesn't seem I can have two ATAC samples from B and C and two RNA from A and B.

**Comment by Jeff1995** [comment]
Thanks for the clarification!

Now I get it, but as far as I know the code does allow different batches in different modalities. You can specify batch information for each dataset separately via [`configure_dataset`](https://scglue.readthedocs.io/en/latest/api/scglue.models.scglue.configure_dataset.html), and they do not need to be the same. E.g., you can even have RNA data from patient A, B, C and ATAC data from patient D, E. The model is going to work just fine.

Did you encounter an error when training the model in such scenarios?

**Comment by ilan-gold** [comment]
Yes! It's possible I haven't tried in a moment, though? Let me give it a whirl and I will get back to you.

**Comment by Jeff1995** [comment]
Sure! The expected behavior is that the model can deal with these cases. You can post error messages here if it failed. I will look into it.

**Comment by ilan-gold** [comment]
I got `RuntimeError: Batches must match when using `shared_batches`!` when trying to fit a GLUE model

**Comment by ilan-gold** [comment]
Yes!

**Comment by ilan-gold** [comment]
Yes!

**Comment by Jeff1995** [comment]
Okay that's why the error is showing up. Currently, `shared_batches` can only be set to `True` when the batches match exactly in different modalities. Otherwise you would have to leave it as `False`.

**Comment by Jeff1995** [comment]
Yes batch correction still works even if `shared_batches` is off. The batch correction mechanism works by incorporating batch as a covariate in the decoder (similar to scVI). Enabling `shared_batches` provides an extra level of guarantee that cells from the same batch are adversarially aligned, but for now that's only supported if batches match exactly.
