### ISSUE TITLE
help for example data

### ISSUE THREAD

**Issue by wiredosprout** [gao-lab/GLUE#29]
Hi, is it possible to help upload the example data "Luo-2017.h5ad" and "10x-ATAC-Brain5k.h5ad" that you used in TripleOmics to pku ftp as well?

Thx a lot! Really amazing manuscript!

**Comment by Jeff1995** [comment]
Thanks for your interest! We are requesting the original authors for redistribution approval. I'll let you know when the files are available for download.

**Comment by wiredosprout** [comment]
Thank you so much! Really appreciate it!
