### ISSUE TITLE
Multiple data integration

### ISSUE THREAD

**Issue by WhaleGe** [gao-lab/GLUE#33]
I have scATAC and scRNA from multiple different samples, can I directly integrate them with glue?

**Comment by Jeff1995** [comment]
Of course! Just give it a try following the [tutorials](https://scglue.readthedocs.io/en/latest/tutorials.html). If you want to correct for the inter-sample batch effect, you can set `use_batch` in [`scglue.models.configure_dataset`](https://scglue.readthedocs.io/en/latest/api/scglue.models.scglue.configure_dataset.html).

Let me know if there are further issues.
