### ISSUE TITLE
ValueError: Expected value argument (Tensor of shape (128, 2000))

### ISSUE THREAD

**Issue by WhaleGe** [gao-lab/GLUE#35]
ValueError: Expected value argument (Tensor of shape (128, 2000)) to be within the support (IntegerGreaterThan(lower_bound=0)) of the distribution NegativeBinomial(total_count: torch.Size([128, 2000]), logits: torch.Size([128, 2000])), but found invalid values:
![image](https://user-images.githubusercontent.com/32753674/174935982-36e524ee-c44c-4dd5-b09b-e24d58283759.png)

**Comment by WhaleGe** [comment]
Have you encountered this problem?

**Comment by WhaleGe** [comment]
I use the raw counts data，but it still gives an error
![image](https://user-images.githubusercontent.com/32753674/174940020-977233a3-5bec-4bac-b20c-6667c1cec77f.png)

**Comment by Jeff1995** [comment]
Thanks for the report! Could you verify that rna.layers["counts"] and atac.layers["counts"] contain all integers?

**Comment by Jeff1995** [comment]
Sure I will look into this. Just to make sure, are these RNA and ATAC data that you are trying to integrate? What kind of preprocessing did you use? It would be most helpful if you could provide something like a jupyter notebook of your analysis.

**Comment by WhaleGe** [comment]
> Sure I will look into this. Just to make sure, are these RNA and ATAC data that you are trying to integrate? What kind of preprocessing did you use? It would be most helpful if you could provide something like a jupyter notebook of your analysis.

These two data are from different samples (the same patient), not Multiomics data. The initial data inside is the counts matrix, and the preprocessing is performed according to the tutorial. I didn't use jupyter to run, but I can show you the code.
```python
rna = sc.read_loom("test/01.rawdata/P11_T_0_rna.loom", sparse=True, cleanup=False, X_name='spliced', obs_names='CellID', var_names='Gene', dtype='float32')
atac = sc.read_loom("test/01.rawdata/P11_T_0_atac.loom", sparse=True, cleanup=False, X_name='spliced', obs_names='CellID', var_names='Gene', dtype='float32')

rna.X, rna.X.data

rna.X = rna.layers["counts"]
rna.layers["counts"] = rna.X.copy()  # If don't assign it back, the next processing will change the data in counts

sc.pp.highly_variable_genes(rna, n_top_genes=2000, flavor="seurat_v3")
sc.pp.normalize_total(rna)
sc.pp.log1p(rna)
sc.pp.scale(rna)
sc.tl.pca(rna, n_comps=100, svd_solver="auto")

sc.pp.neighbors(rna, metric="cosine")
sc.tl.umap(rna)
sc.pl.umap(rna, color="celltype_singlesamp",save='_rna.pdf')

scglue.data.lsi(atac, n_components=100, n_iter=15)
sc.pp.neighbors(atac, use_rep="X_lsi", metric="cosine")
sc.tl.umap(atac)
sc.pl.umap(atac, color="Celltype",save='_atac.pdf')

scglue.data.get_gene_annotation(
    rna, gtf="./1.database/Reference/refdata-gex-GRCh38-2020-A/genes/genes.gtf.gz",
    gtf_by="gene_name"
)
rna.var.loc[:, ["chrom", "chromStart", "chromEnd"]].head()
ann_genes_list = rna.var[~rna.var.loc[:, ["chrom"]].isnull().iloc[:,0]].index.values.tolist() #Extract annotated genes
rna = rna[:,ann_genes_list]

atac.var_names[:5]
split = atac.var_names.str.split(r"[:-]")
atac.var["chrom"] = split.map(lambda x: x[0])
atac.var["chromStart"] = split.map(lambda x: x[1])
atac.var["chromEnd"] = split.map(lambda x: x[2])
atac.var.head()

graph = scglue.genomics.rna_anchored_prior_graph(rna, atac)
graph

graph.number_of_nodes(), graph.number_of_edges()
# Graph node covers all omic features
all(graph.has_node(gene) for gene in rna.var_names), \
all(graph.has_node(peak) for peak in atac.var_names)
# Edge attributes contain weights and signs
for _, e in zip(range(5), graph.edges):
    print(f"{e}: {graph.edges[e]}")

# Each node has a self-loop
all(graph.has_edge(gene, gene) for gene in rna.var_names), \
all(graph.has_edge(peak, peak) for peak in atac.var_names)

# Graph is symmetric
all(graph.has_edge(j, i) for i, j, _ in graph.edges)
atac.var.head()

scglue.models.configure_dataset(
    rna, "NB", use_highly_variable=True,
    use_layer="counts", use_rep="X_pca"
)

scglue.models.configure_dataset(
    atac, "NB", use_highly_variable=True,
    use_layer="counts",use_rep="X_lsi"
)

glue = scglue.models.fit_SCGLUE(
    {"rna": rna, "atac": atac}, graph,
    fit_kws={"directory": "glue"}
)

glue.save("glue.dill")
# glue = scglue.models.load_model("glue.dill")

dx = scglue.models.integration_consistency(
    glue, {"rna": rna, "atac": atac}, graph,
    count_layers={"rna": "counts"}
)
dx
```

**Comment by Jeff1995** [comment]
Thanks a lot! There's nothing wrong about the code. Could you help check the loss values in tensorboard? You can do so with `tensorboard --logdir=glue` and then open the web page in a browser.

**Comment by WhaleGe** [comment]
> Thanks a lot! There's nothing wrong about the code. Could you help check the loss values in tensorboard? You can do so with `tensorboard --logdir=glue` and then open the web page in a browser.

**Could you help me see it, I really don't understand，thank you very much**

![image](https://user-images.githubusercontent.com/32753674/175484128-44fbc944-97b8-428f-818b-1eacc203d135.png)
![image](https://user-images.githubusercontent.com/32753674/175484193-4f82b75b-5518-4fe3-88da-7ceb9226bb5f.png)

**Comment by Jeff1995** [comment]
Thanks! The loss values are also mostly nominal, especially that the discriminator loss have indeed converged at around `ln(2) = 0.693`.

This is inconsistent with the UMAP plot you posted earlier. Could you also post your code after model training, corresponding to the ["Apply model" section in the tutorial](https://scglue.readthedocs.io/en/latest/training.html#Apply-model-for-cell-and-feature-embedding)?

Is it possible that you accidentally skipped the following lines:

```python
sc.pp.neighbors(combined, use_rep="X_glue", metric="cosine")
sc.tl.umap(combined)
```

That would cause it to visualize the UMAP of unimodal spaces (RNA PCA and ATAC LSI) superimposed over each other, rather than the UMAP of the GLUE-integrated space.

**Comment by WhaleGe** [comment]
You are right, I repainted the umap and it shows up really well. I would like to ask you, what method do I use to identify the differences between clusters for downstream analysis. In addition, I found that the data in combined.X does not exist anymore.

![image](https://user-images.githubusercontent.com/32753674/175512751-bbf2edee-c011-419c-acbe-8ed5d341e08d.png)

**Comment by Jeff1995** [comment]
Great! Yes the `combined` object does not have an `X`. It can only be used to visualize and cluster low-dimensional projections. You can obtain joint clusters using `scanpy` over `combined.obsm["X_glue"]`. For downstream differential analysis, I would recommend using `scanpy` over the RNA modality, and `muon` or `episcanpy` over the ATAC modality.

**Comment by WhaleGe** [comment]
OK，thank you very much

**Comment by LalicJ** [comment]
@WhaleGe Hi, sorry to bother you. I met the same error: 
```
Expected value argument (Tensor of shape (128, 3428)) to be within the support (IntegerGreaterThan(lower_bound=0)) of the distribution NegativeBinomial(total_count: torch.Size([128, 3428]), logits: torch.Size([128, 3428])), but found invalid values:
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
```
Do you have any suggestions? Because I saw you had solved this problem.
