### ISSUE TITLE
Some questions about GLUE evaluation process

### ISSUE THREAD

**Issue by HelloWorldLTY** [gao-lab/GLUE#37]
Hi, I finally generated the model of glue, but met a new problem:
In this code:
![image](https://user-images.githubusercontent.com/43333475/175451797-ea4abd86-dbef-47f8-a41a-7a00e16d8758.png)
I meet this problem:
![image](https://user-images.githubusercontent.com/43333475/175451755-448cddb4-c04e-4f47-abb7-31bbe9c0b6cf.png)
I think it may be caused by the sparse data type of counts data:
![image](https://user-images.githubusercontent.com/43333475/175451961-5cf6b577-3adf-46f6-b984-64001a008a84.png)
Could you please help me? Thanks a lot.

**Comment by Jeff1995** [comment]
Is this the same problem as #27? Could you check the scanpy version?

**Comment by HelloWorldLTY** [comment]
Oh, yes, it is pretty strange because I passed the previous check. I will try again later. Thanks a lot.
