### ISSUE TITLE
Integrating CyTOF data with the graph based on scRNA-seq and scATAC-seq

### ISSUE THREAD

**Issue by sohrabsa** [gao-lab/GLUE#38]
Hi, I have been able to successfully use GLUE to integrate un-paired scRNAseq and scATACseq data.
I was wondering if you have any pointers on using GULE to construct the guidance graph with CyTOF as a third data modality. 

Thank you!

**Comment by Jeff1995** [comment]
Great to hear that! For protein measurements in CyTOF, I would recommend adding protein vertices connected to their corresponding genes in the guidance graph.

One more thing to consider is the generative distribution. I'm not familiar with CyTOF data. What's the data distribution typically used to model CyTOF measurements? We would need to implement a new one if it is not currently available in `scglue`.
