### ISSUE TITLE
Integrate Spatial data

### ISSUE THREAD

**Issue by Lycidas97** [gao-lab/GLUE#39]
Thank you for developing such a great tool! I'm working on integrating single cell and spatial transcriptomic data using GLUE. Because they have same var_name(gene name), it is confusing when it comes to prior graph building. I wonder whether I should generate vertice for each dataset, for example, in form of gene_name-dataset , or just build a graph that has gene name as vertices and only contains self-loop?

**Comment by Jeff1995** [comment]
Thanks for your interest in GLUE!

We haven't tested the model on spatial data yet, but I think either way should work. You may try the latter first (build a graph that has gene name as vertices and only contains self-loop) which is simpler.

I'm also curious about any performance difference, so please let us know your experience along this approach. It will also be useful for future users 😀.
