### ISSUE TITLE
Bedtools cannot be matched

### ISSUE THREAD

**Issue by XUEbaogai0101** [gao-lab/GLUE#43]
Hi , thanks for the very helpful package!
I have used the method in the https://github.com/gao-lab/GLUE/issues/22#issuecomment-1161983847, but it didn't solve my question.Could you give me a help?Thanks!
BEST!
XUE
![image](https://user-images.githubusercontent.com/103372530/180878099-3ed8564c-ec9d-4247-adb3-12abe15655fd.png)
![image](https://user-images.githubusercontent.com/103372530/180878182-8ecd9912-0948-4f1f-ba8e-3ebe1d656906.png)

**Comment by XUEbaogai0101** [comment]
I can run the code in the ipython at the same conda environment, is there any wrong with my jupyter Lab?
Cause the Lab was installed by root, I doubt something wrong with the pathway of the bedtools in the Lab. How could I fixed it?
![image](https://user-images.githubusercontent.com/103372530/180881683-ad66a591-e918-4c19-bab4-9a82c01ee45d.png)

**Comment by XUEbaogai0101** [comment]
![image](https://user-images.githubusercontent.com/103372530/180882207-7b1e2dfb-5674-4dc8-b3fd-133dbf67f6c3.png)

**Comment by Jeff1995** [comment]
Thanks for your interest in GLUE! 

The `scglue.config.BEDTOOLS_PATH` should be set to the bedtools executable itself, rather than the bin directory.

```py
scglue.config.BEDTOOLS_PATH = "/data/user/xhw/miniconda3/envs/scglue/bin/bedtools"
```

**Comment by XUEbaogai0101** [comment]
![image](https://user-images.githubusercontent.com/103372530/180912785-f526e40d-7ba8-4903-b441-2fd26415e24c.png)
The results was the same.

**Comment by XUEbaogai0101** [comment]
I tried to change the code as follow, but it didn't work. 
```
CHECKERS = dict(
    bedtools=CmdChecker(
        "bedtools", f"{‘/data/user/xhw/miniconda3/envs/scglue/bin/bedtools’} --version", r"v([0-9\.]+)",
        vmin="2.29.2", install_hint=INSTALL_HINTS.bedtools
    ),
    plotly=ModuleChecker(
        "plotly",
        vmin=None, install_hint=INSTALL_HINTS.plotly
    )
)
```

**Comment by Jeff1995** [comment]
Well that's strange. Could you confirm that the executable file "/data/user/xhw/miniconda3/envs/scglue/bin/bedtools" exists? E.g., check `ls /data/user/xhw/miniconda3/envs/scglue/bin/bedtools`.

Meanwhile, the code change should be:

```py
CHECKERS = dict(
    bedtools=CmdChecker(
        "bedtools", "/data/user/xhw/miniconda3/envs/scglue/bin/bedtools --version", r"v([0-9\.]+)",
        vmin="2.29.2", install_hint=INSTALL_HINTS.bedtools
    ),
    plotly=ModuleChecker(
        "plotly",
        vmin=None, install_hint=INSTALL_HINTS.plotly
    )
)
```

And you would need to restart the jupyter kernel to make the code change effective (reimporting scglue will not work).

**Comment by XUEbaogai0101** [comment]
I have done all the suggestions you gived as follow, but it seemed no working.
![image](https://user-images.githubusercontent.com/103372530/180949846-826cdefe-5f12-41b8-8190-326c3e7b591d.png)
![image](https://user-images.githubusercontent.com/103372530/180950012-96b8c08e-0bea-4bb7-aa2b-af2afd8cc146.png)
![image](https://user-images.githubusercontent.com/103372530/180950401-64aaef04-2bd3-4c29-908f-3661868be817.png)

**Comment by XUEbaogai0101** [comment]
I have finished the data processing in the ipython, it worked well.  So the problem doesn't matter. Thanks for your nice job and patience.
BEST!
XUE

**Comment by Jeff1995** [comment]
Okay great! Let me know if there are further issues though.
