### ISSUE TITLE
How do I run Evalution using PBS scheduling system in HPC?

### ISSUE THREAD

**Issue by dingjunxiang** [gao-lab/GLUE#47]
I can only use the HPC cluster using PBS scheduling system, I should modify what files to be able to run Evalution?

**Comment by Jeff1995** [comment]
Thanks for your interest in GLUE! You would need to modify the following two files:

* [evaluation/profiles/cls/config.yaml](https://github.com/gao-lab/GLUE/blob/master/evaluation/profiles/cls/config.yaml)
* [evaluation/profiles/cls/cls.yaml](https://github.com/gao-lab/GLUE/blob/master/evaluation/profiles/cls/cls.yaml)

I'm not familiar with PBS, but the following docs of snakemake may also be helpful:

* https://snakemake.readthedocs.io/en/stable/executing/cluster.html#cluster-execution
* https://snakemake.readthedocs.io/en/stable/tutorial/additional_features.html#cluster-execution
* https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#cluster-configuration-deprecated

Let me know if there are further issues!
