### ISSUE TITLE
Guide on constructing guidance graph

### ISSUE THREAD

**Issue by sshen82** [gao-lab/GLUE#48]
Hi,
Thank you for this great method! I have a question on specifically how to construct a guidance graph manually. In my setting, I directly create a data frame called reg2gene that is shown as:

'0'          '1'
gene1 region1
gene2 region2
......

How can I convert this data frame into a graph that can be used in your method? I tried to use G = nx.from_pandas_edgelist(reg2gene, 0, 1), but the resulting graph doesn't seem able to be used in GLUE.

Yours sincerely,
Siqi Shen

**Comment by Jeff1995** [comment]
Hi Siqi!

Thanks for your interest in GLUE! What's the error you are getting?

Generally speaking, you need to ensure the following things before feeding the graph to GLUE:

1. Edges in the graph should contain attributes "weight" and "sign". You can do so by using a data frame like below:
   ```
   source target weight sign
   gene1 region1 1.0 1
   gene2 region2 0.8 -1
   ```
   And then convert it to networkx via:
   ```py
   G = nx.from_pandas_edgelist(reg2gene, edge_attr=True)
   ```
2. You need to make sure that the graph contains self-loops with `weight=1.0` and `sign=1`. If your graph does not have self-loops already, you may do so via:
   ```py
   for node in G.nodes:
       G.add_edge(node, node, weight=1.0, sign=1)
   ```

Let me know if there are further issues!

**Comment by sshen82** [comment]
I didn't have weight and sign columns, since they are all one in default. I will try this. Thank you!
