### ISSUE TITLE
question for cell  embedding with multiomics data

### ISSUE THREAD

**Issue by Dragonlongzhilin** [gao-lab/GLUE#49]
Thanks for developing a nice tool! I used glue to integrate scRNA-seq and scATAC-seq datasets from multiple samples. I want to get clustering results covering both modalities in the umap plot. 
What can I do to get this information? Can I do clustering on embedding space？
Can I come up with batch-corrected data for clustering？

**Comment by Jeff1995** [comment]
Thanks for your interest in GLUE! Yes you can use the cell embeddings for clustering. E.g., in `scanpy` the following should do:

```py
combined = ad.concat([rna, atac])
sc.pp.neighbors(combined, use_rep="X_glue")
sc.tl.leiden(combined)
```

For batch correction you can specify the batch covariate via `use_batch` in [`configure_dataset`](https://scglue.readthedocs.io/en/latest/api/scglue.models.configure_dataset.html).

Let me know if there were other issues!
