### ISSUE TITLE
Problems in visualizing the regulatory inference graph

### ISSUE THREAD

**Issue by Thomaswbt** [gao-lab/GLUE#52]
Hi!
I followed your tutorial and had problems replicating the regulatory inference step (step 3). To be specific, in Code Block number 12 following your tutorial https://scglue.readthedocs.io/en/latest/training.html (see the upper fig), I found that pyGenomeTracks cannot properly generate the inference graph because there is a problem handling the input RNA sequence. There seems to be a problem when constructing an Interval object using the RNA data (see the error message in the lower fig). I replicated this error message on 2 different machines and can confirm that this is not a problem due to typos. Could you please check whether you can replicate this problem? I guess there might be conflicts with other package dependencies or there might be some errors in the RNA sequence itself. I strictly follow the step 1 and step 2 of your tutorial and could perfectly replicate them. Thanks a lot in advance!
<img width="721" alt="屏幕快照 2022-10-28 下午11 02 18" src="https://user-images.githubusercontent.com/55548313/198671269-54d2352b-7309-41a4-a9bb-ae27eb968f3c.png">
<img width="1541" alt="屏幕快照 2022-10-27 下午7 55 29" src="https://user-images.githubusercontent.com/55548313/198671288-40b05a50-0253-4161-b6c2-56244b77b090.png">

**Comment by Jeff1995** [comment]
Thanks for the report! This is a pyGenomeTracks bug. I patched it in my local lib a while ago and forgot about it. I have now made a PR in pyGenomeTracks (deeptools/pyGenomeTracks#423). Hopefully it will be fixed in their next release 😀.

In the meantime, you may also apply the patch in your own local lib by modifying the pygenometracks/tracks/LinksTrack.py file as in deeptools/pyGenomeTracks#423.

**Comment by Thomaswbt** [comment]
Thank you for your reply! 
I saw that your patch has already been accepted by pyGenomeTrack. I really appreciate your efforts！👍👍 
I haven't tried to add the patch manually but the bug will hopefully be resolved with their next release, so I'll close the issue.

**Comment by Jeff1995** [comment]
PyGenomeTracks has made a new release ([v3.8](https://github.com/deeptools/pyGenomeTracks/releases/tag/3.8)). The issue should be resolved with that update.
