### ISSUE TITLE
Question about running gpu

### ISSUE THREAD

**Issue by fe4960** [gao-lab/GLUE#55]
Hello,

I am following the tutorial to preprocess snRNA-seq and snATAC-seq data. The steps below have not finished after 16 hours.

scglue.data.lsi(atac, n_components=100, n_iter=15)
sc.pp.neighbors(atac, use_rep="X_lsi", metric="cosine")
sc.tl.umap(atac)
sc.pl.embedding(atac, basis="X_umap",color=[label_atac], ncols=1,frameon=False,save=f'_{cell}_atac.png', palette="tab20")

There are 66532 cells and 462718 peaks in snATAC-seq. The code seems not be able to use gpu, are running with 8 CPU and use a lot of memory. I wonder if you know the reason why it took so long to run these steps. I have installed pytorch-gpu, but it seems there is no option/parameter to call gpu for scGlue. Could you let me know how to run scGlue with gpu? 

Also, I wonder how to set seed for scGlue to reproduce the results.

Thanks a lot!

**Comment by Jeff1995** [comment]
Thanks for your interest in GLUE! The preprocessing steps cannot utilize GPU, but a 66532 * 462718 matrix should not take more than a couple of minutes. Could you verify that the count matrix is in a sparse format? If it's densely stored it would take more time and memory. You may also run these line by line to see which line exactly is taking the most time.

**Comment by fe4960** [comment]
Thanks a lot for the reply! The count matrix is in a sparse format.
