### ISSUE TITLE
Significant links in the regulatory graph for RNA + CNV integration

### ISSUE THREAD

**Issue by Laolga** [gao-lab/GLUE#57]
Hi! I'm using scglue to find shared variation between gene expression and CNV changes. The main change to the published tutorial is that I've connected gene to a region (from CNV data) in the guidance graph if the gene is inside that region. Plus I computed z-scores of CNs and then used normal distribution to configure the CNV dataset.

So judging from the feature embedding, the data was integrated pretty well: all major DNA clones clustered together while RNA-based cell types also remained closely connected. The consistency score is also way above 0.05.

What seems strange to me is that no regulatory links appear to be significant, e.g. all q-values are quite below 0.05. Could you please help me to understand why is that? Or help me to interpret this somehow. Maybe there is something more I can learn from the data that I don't see yet.

**Comment by Jeff1995** [comment]
Thanks for the question! Just to make sure, do you mean that all q-values are quite **above** 0.05, so none of these are significant? We've never tried integrating RNA + CNV data. It would be helpful if you could provide some extra information like:

* The number of HVGs used in the analysis
* The number of CNV regions involved
* The number of nodes and edges in the guidance graph

It would be best if you could also share the guidance graph itself, the feature embeddings, as well as the resulting regulatory scores and p-values, so I can take a closer look.

**Comment by Laolga** [comment]
Thanks for your reply! Yes, exactly: many edges have a high score, but qvalues are all above 0.05. 
I've selected the union of variable genes (RNA) and variable CNVs for the guidance graph (4651 nodes in total). I can share the guidance graph, rna and dna embedding and the graph with regulatory scores: https://www.dropbox.com/sh/g8ka0nxmckxm7xp/AAByr1wKN0XpOKfpScSyI0Rha?dl=0
