### ISSUE TITLE
Building rna-atac graph: ValueError: Not all features are strand specific!

### ISSUE THREAD

**Issue by jules-samaran** [gao-lab/GLUE#58]
Dear authors, 
I encountered this issue as I was trying to integrate single-cell RNA and ATAC when running `scglue.genomics.rna_anchored_guidance_graph`.

As you can see (head -5) the columns "chrom  chromStart  chromEnd" are present in both the rna anndata

                                  gene_ids                      interval              chrom  chromStart  chromEnd
AL627309.1  ENSG00000238009  chr1:120931-133723      chr1        120931    133723
AL627309.5  ENSG00000241860  chr1:149706-173862      chr1        149706    173862
LINC01409   ENSG00000237491  chr1:778757-803934      chr1        778757    803934
LINC01128   ENSG00000228794  chr1:827597-860227      chr1        827597    860227
LINC00115   ENSG00000225880  chr1:827521-827522      chr1        827521    827522

and the atac anndata

                                         chrom  chromStart  chromEnd
chr1:9790-10675             chr1        9790     10675
chr1:180599-181702      chr1      180599    181702
chr1:191168-192093      chr1      191168    192093
chr1:267565-268455      chr1      267565    268455
chr1:270876-271770      chr1      270876    271770

But when I run `guidance_graph = scglue.genomics.rna_anchored_guidance_graph(rna, atac)`, I get the error:

 **File "/users/csb/samaran/miniconda3/envs/uniport/lib/python3.7/site-packages/scglue/genomics.py", line 533, in rna_anchored_guidance_graph
    rna_bed = rna_bed.expand(promoter_len, 0)
  File "/users/csb/samaran/miniconda3/envs/uniport/lib/python3.7/site-packages/scglue/genomics.py", line 221, in expand
    raise ValueError("Not all features are strand specific!")
ValueError: Not all features are strand specific!**

 The "strand" information is not present in the anndata I'm providing, is it necessary that I add it before using scGLUE?

**Comment by Jeff1995** [comment]
Thanks for your interest in GLUE! By default, the guidance graph is built based on ATAC overlap with gene promoter + gene body. The "strand" information is required for the RNA data to determine the location of the promoter.

**Comment by jules-samaran** [comment]
Thanks for you answer!
