### ISSUE TITLE
question about snmC-seq

### ISSUE THREAD

**Issue by dandata123-tech** [gao-lab/GLUE#59]
Hi, Zhijie:
Your work is excellent but I have some questions about snmC-seq:
How can I integrate this data into our model, I haven't found this aspect when I read our tutorial.Could you tell me how to solve it?
Thanks, looking forward to your reply.

**Comment by Jeff1995** [comment]
Hi Dan,

Thanks for your interest in GLUE! We used both "gene_level_mouse.txt.gz" and "mCG_genebody_mouse.txt.gz", the former for mCH level quantification, the latter for mCG level quantification. You may find the details in this [data collection notebook](https://github.com/gao-lab/GLUE/blob/master/data/collect/Luo-2017.ipynb).

Let me know if there were further issues.

Best,
Zhi-Jie

**Comment by Jeff1995** [comment]
Ideally speaking, smaller bins should produce higher resolution both in terms of cell integration and regulatory inference, but with the following two caveats: 

1. Smaller bins would produce far more nodes (20 times 5kb bins compared to 100kb) in the guidance graph, which would definitely have an impact on integration speed;
2. Smaller bins have lower single-cell detectability compared to larger bins, so there might be higher "dropout" rate and lower ability to discern cell states/types.

I'd recommend checking these two aspects before deciding on the bin size.
