### ISSUE TITLE
Download link failed

### ISSUE THREAD

**Issue by YahaoDing** [gao-lab/GLUE#62]
Hello!

I want to study about this interesting software. So I try to do as the tutorial shows but I find I can't download the data. I clicked the links but nothing happened. I wonder how I can get the data. The links are 

http://download.gao-lab.org/GLUE/tutorial/Chen-2019-RNA.h5ad
http://download.gao-lab.org/GLUE/tutorial/Chen-2019-ATAC.h5ad

Thank you very much and sorry for disturbing you.
YahaoDing

**Comment by Jeff1995** [comment]
Hi Yahao! Thanks for your interest in GLUE. I have just tested the links and they seem to work just fine. Could you try again using a different browser or downloading via the command line (e.g., `wget`, `curl`)? It might as well be an intermittent connection problem.

**Comment by YahaoDing** [comment]
Thank you! I used Chrome and it did not work. Now I use Edge and I get the data. Thank you very much!
