### ISSUE TITLE
Help with code

### ISSUE THREAD

**Issue by Dan-121** [gao-lab/GLUE#65]
Hi Zhijie,

I noticed that your work on GLUE mentioned eQTL and Hi-C. Would you be so kind as to tell me where I can find your script?

Thank you very much.

Dan

**Comment by Jeff1995** [comment]
Hi @dandata123-tech! The code can be found in this [directory](https://github.com/gao-lab/GLUE/tree/master/experiments/RegInf). 

`s01_preprocessing.py` contains the relevant code mapping Hi-C and eQTL data into GLUE useable graph objects.
