### ISSUE TITLE
Some questions about latent space dimensions

### ISSUE THREAD

**Issue by HelloWorldLTY** [gao-lab/GLUE#7]
Dear Dr. Cao,

Sorry to disturb you again. I take a look at the code you used in the NeuriPS competition and I wonder why you choose to reduce the input dimensions from 100 to 50 as latent space? It seems that  you only reduced half of the original space. From my perspective, this approach may not help to improve the performance of the final matching.

Thanks a lot!

**Comment by Jeff1995** [comment]
For the CLUE model in the competition, the encoder input space were 100-dim PCA/LSI. The latent space dimension differed per task. We used 20-dim for CITE and 50-dim for Multiome. Nevertheless, these dimensionalities specified the latent dimension of each individual encoder in the "encoder matrix" (Mod1->Mod1, Mod1->Mod2, Mod2->Mod1, Mod2->Mod2). The final embedding was concatenated for each modality, so it's 40-dim for CITE and 100-dim for Multiome.

In our hyperparameter optimization, this was the optimal setting, though the performance change of dimensionality tuning wasn't particularly significant. My reasoning is that the non-linear encoders could further compress the information from the linear PCA/LSI space, so there isn't much information loss across a reasonable range of latent dimensionalities.

**Comment by HelloWorldLTY** [comment]
Thanks for your information, I also agree that dimensions will not affect results a lot.

**Comment by Jeff1995** [comment]
You're welcome! Let me know if any further issues.
