### ISSUE TITLE
questions about dataencoder of CLUE

### ISSUE THREAD

**Issue by bestadcarry** [gao-lab/GLUE#70]
Hi @Jeff1995, I have a question regarding [CLUE](https://xinmingtu.cn/assets/pdf/clue_paper.pdf) that I was hoping you could help me with. I don't understand what functions **compute_l** and **normalize** are used for in the CompositeDataEncoder of CLUE. Could you please explain it in detail? e.g., their use in NBCompositeDataEncoder. Thank you so much!

**Comment by Jeff1995** [comment]
Hi @bestadcarry! The purpose of these functions is to parameterize decoded counts as _softmax-normalized proportions_ multiplied by _library size_. I believe it's a trick originally introduced in [scVI](https://github.com/scverse/scvi-tools) to help factorize out the influence of sequencing depth and improve training stability.
