### ISSUE TITLE
Multiple batch variables

### ISSUE THREAD

**Issue by sinkahak** [gao-lab/GLUE#76]
Hi,

Thanks for an exciting software!

I was wondering if it was possible to use multiple data batches for batch correction in scglue.models.configure_dataset() ? My own efforts to do that have failed.

Best,
Sini

**Comment by Jeff1995** [comment]
Hi @sinkahak. Thanks for your interest in GLUE!

GLUE does not support multiple batch covariates for now, but one way to make it work is to concatenate the different batch covariates. E.g., you may have two batch covariates like below:

|Donor|Sequencing run|
|:-:|:-:|
|d1|b1|
|d1|b2|
|d2|b1|
|d2|b2|

You may concatenate them into one batch covariate:

|Concatenated batch|
|:-:|
|d1-b1|
|d1-b2|
|d2-b1|
|d2-b2|

Would that solve the problem?

**Comment by sinkahak** [comment]
Thanks, I will give that a try!

**Comment by sinkahak** [comment]
Thanks, I will give that a try!
