### ISSUE TITLE
Looking for the last step in the GLUE framework.

### ISSUE THREAD

**Issue by vietdhoang** [gao-lab/GLUE#83]
This may be a dumb question, but in the last step of Fig. 1of the paper, there is a step where data decoders reconstruct the data via inner product of cell and feature embeddings. Does the tutorial cover that and if so, at which step?

Thanks!

**Comment by Jeff1995** [comment]
Hi @vietdhoang! Thanks for your interest in GLUE.

The reconstruction step is part of the model training procedure, but not the final output. The output of the model is the cell and feature embeddings learned after training.

With that said, though this is not currently supported by the package, you may certainly do data reconstruction by feeding the cell and feature embeddings to the data decoder. I can add a dedicated function for that if that's what you need.

**Comment by vietdhoang** [comment]
I see, if the cell and feature embedding are the 'final' output, then I'm happy! It would be nice to see the data reconstruction though.
