### ISSUE TITLE
CLUE paper reproducibility code

### ISSUE THREAD

**Issue by valentinwust** [gao-lab/GLUE#84]
In the supplementary material to the [CLUE paper](https://papers.nips.cc/paper_files/paper/2022/hash/662b1774ba8845fc1fa3d1fc0177ceeb-Abstract-Conference.html), you mention a .zip file with all the relevant code; however I can't find this anywhere. Did you use the exact same setup as [published on the competition git](https://github.com/openproblems-bio/neurips2021_multimodal_topmethods/tree/main/src/match_modality/methods/clue)? I'm trying to run some benchmarks and want to stay as close to your paper as possible.

Greetings
Valentin

**Comment by Jeff1995** [comment]
Hi @valentinwust! Yes that's the identical setup as the competition git.

**Comment by valentinwust** [comment]
Thank you, then I'll probably just use that. That being said, this uses scclue 0.1.1, and I've noticed some slight changes in the code of CLUE since then. Do they meaningfully affect the preformance?

**Comment by Jeff1995** [comment]
Actually that was not 0.1.1, but a version between 0.1.1 and 0.2.0. We didn't tag it as a dedicated public release. To exactly reproduce the CLUE model in the competition, I'd suggest using the [whl file](https://github.com/openproblems-bio/neurips2021_multimodal_topmethods/blob/main/src/match_modality/methods/clue/resources/scglue-0.1.1-py3-none-any.whl) in the competition repo to install `scglue`. Apologies for the inconvenience.

**Comment by valentinwust** [comment]
No problem, this is indeed what I am currently doing. I was just wondering whether the current release (0.3.2) would perform better or similar, if it has a relevant performance increase it might make sense to use the most current version instead.

**Comment by Jeff1995** [comment]
Great! There shouldn't be a noticeable performance difference. You may just use the whl version to avoid needing to change some of the function calls due to API changes along the way.
