### ISSUE TITLE
Would it be possible to ensure specific conditions are matched for a metacell between scRNA and scATAC datasets 

### ISSUE THREAD

**Issue by revolvefire** [gao-lab/GLUE#88]
Thanks for the wonderful tool!

I have multiple time-series scRNA and scATAC datasets, and I was wondering whether it would be possible to ensure that a certain condition, in this case "day" of the sample, could be matched when creating a meta cell.

So for example, if I have unpaired scRNA and scATAC datasets from developmental day1, 2, and 3, integrate scRNA and scATAC data separately, then try to use scGLUE, would it be possible to make sure that both data from the same day would be matched? Obviously the information of the day would be included in each adata.

I want to picture the entire developmental process, hence I integrated each of the RNA and ATAC datasets,
but I'm afraid that data of RNA and ATAC from different days may be conjoined if I go through scGLUE, as there is only delicate change during the timespan of development. 

If what I aim is not possible with the current settings, would there be any other way to approach this matter that you could recommend?

Best!

**Comment by Jeff1995** [comment]
Hi @revolvefire! Sorry for the late response. To ensure that meta cells are constructed from cells of the same day, you can split the dataset into three days, use the [`get_metacells`](https://scglue.readthedocs.io/en/latest/api/scglue.data.get_metacells.html) function on each day, and then concatenate the results back together. Below is a rough example:

```py
# Train integration model
glue = scglue.models.fit_SCGLUE({"rna": rna, "atac": atac}, guidance)
rna.obsm["X_glue"] = glue.encode_data("rna", rna)
atac.obsm["X_glue"] = glue.encode_data("atac", atac)

# Split days
rna1 = rna[rna.obs.day == 1]
rna2 = rna[rna.obs.day == 2]
rna3 = rna[rna.obs.day == 3]
atac1 = atac[atac.obs.day == 1]
atac2 = atac[atac.obs.day == 2]
atac3 = atac[atac.obs.day == 3]

# Construct metacells per day
rna1_meta, atac1_meta = get_metacells(rna1, atac1, use_rep="X_glue")
rna2_meta, atac2_meta = get_metacells(rna2, atac2, use_rep="X_glue")
rna3_meta, atac3_meta = get_metacells(rna3, atac3, use_rep="X_glue")

# Merge days
rna_meta = anndata.concat([rna1_meta, rna2_meta, rna3_meta])
atac_meta = anndata.concat([atac1_meta, atac2_meta, atac3_meta])
```

In this example, I trained the integration model with all cells simultaneously. Of course you can also train models for each day, as long as there is a sufficient number of cells.

**Comment by revolvefire** [comment]
Wonderful! thanks for the detailed answer!
