### ISSUE TITLE
Training with long-range guidance graph

### ISSUE THREAD

**Issue by valentinwust** [gao-lab/GLUE#89]
Hello,

I am trying to reproduce Fig.4 from your GLUE paper. Is there anything about the code that needs to be changed when training with a long-range guidance graph that has fractional edge weights, other than using `extend_range` in `rna_anchored_guidance_graph`? The graph appears to contain the correct weights, and from the package code it looks like it should directly use them without further prodding. But the scores I get don't look like it is reconstructing the graph accordingly (the gray line is average edge weight in the graph), and the AUROC also isn't better for them than using correlations:

![GLUEreg](https://github.com/gao-lab/GLUE/assets/44555270/cd31c9ab-f695-44b6-b597-282d760dcfb1)

I am using the same data as you, same celltype subset, your code to process pcHi-C, 6000 highly variable genes with a 150kb window, 100-dim pca/lsi input, average score across four seeds. The integration also looks fine, is there anything I am missing?

Greetings

**Comment by Jeff1995** [comment]
Hi @valentinwust! There were indeed some additional specifics.

1. The guidance graph was constructed [centered around promoters](https://github.com/gao-lab/GLUE/blob/e006de995b0b615d679287e620eaa49e2d8afb3f/experiments/RegInf/s01_preprocessing.py#L137-L144) [(-2kb, 0)](https://github.com/gao-lab/GLUE/blob/e006de995b0b615d679287e620eaa49e2d8afb3f/experiments/RegInf/s01_preprocessing.py#L81), not including gene bodies.
2. For comparison with external evidence (pcHi-C, eQTL) and alternative methods (Cicero), we [took the intersection](https://github.com/gao-lab/GLUE/blob/e006de995b0b615d679287e620eaa49e2d8afb3f/experiments/RegInf/s01_preprocessing.py#L283-L288) between highly variable genes and genes covered by them.

I wonder if these have caused the difference.

**Comment by valentinwust** [comment]
Thank you, how I constructed the graph seems to have indeed been the problem, it works now:

![GLUEreg](https://github.com/gao-lab/GLUE/assets/44555270/bff27cef-05a7-4c4b-9085-57f744161363)
