### ISSUE TITLE
Can Glue be used to integrate single-cell transcriptome, Bulk-proteomics, and metabonomics?

### ISSUE THREAD

**Issue by zydf1996** [gao-lab/GLUE#9]
Dear developers,
Thank you for sharing your code. I want to take this opportunity to ask whether we can use your Glue program to integrate simple single-cell transcriptome with general proteomics and metabonomics. This is very important to me. Thank you for your answer.
Best wishes,
zjz

**Comment by Jeff1995** [comment]
Thanks for your interest in GLUE!

What kind of integration do you intend to do?

Is it more like:

1. Deconvolution of these bulk data with help from scRNA-seq;

Or

2. Unpaired alignment of scRNA-seq and several bulk samples?

If it's the first case, I'm afraid that's not what GLUE is designed for.

In the second case, I think that would depend on how many bulk samples you have. If there is a sufficient number of bulk samples, it would be worth a try.

**Comment by zydf1996** [comment]
> Thanks for your interest in GLUE!
> 
> What kind of integration do you intend to do?
> 
> Is it more like:
> 
> 1. Deconvolution of these bulk data with help from scRNA-seq;
> 
> Or
> 
> 2. Unpaired alignment of scRNA-seq and several bulk samples?
> 
> If it's the first case, I'm afraid that's not what GLUE is designed for.
> 
> In the second case, I think that would depend on how many bulk samples you have. If there is a sufficient number of bulk samples, it would be worth a try.
Thank you so much. What i want to do is the second case. It may take longer to try ^-^.

**Comment by Jeff1995** [comment]
Sure! Let me know if there are further issues.
