### ISSUE TITLE
how to construct guidence between scATAC data and single cell DNA methylation data

### ISSUE THREAD

**Issue by YettaWang** [gao-lab/GLUE#93]
Thank you for creating such an excellent tool. I recently need to integrate single-cell ATAC and single-cell DNA methylation data, and I would like to know how to construct a guidance graph between these two types of data. After carefully reading the tutorial, I found that scglue.genomics.rna_anchored_guidance_graph requires an RNA dataset, while I only want to integrate single-cell ATAC and single-cell DNA methylation data.

**Comment by Jeff1995** [comment]
Hi @YettaWang. Thanks for your interest in GLUE!

What feature space is your DNA methylation data in? Single-cell DNA methylation data are typically sparse in single-C, and need to be aggregated by certain genomic regions (bins, genes, etc.).

If you have already aggregated your DNA methylation data into genomic regions, you may use the [`scglue.genomics.window_graph`](https://scglue.readthedocs.io/en/latest/api/scglue.genomics.window_graph.html) to construct the guidance graph. This function connects features based on genomic overlap with optional padding (window size), pretty similar to `bedtools intersect`. Note that the prior regulatory direction (positive/negative) might be context dependent between DNA methylation and ATAC, and would likely require some extra curation.
