### ISSUE TITLE
cluster analysis on the integrated data

### ISSUE THREAD

**Issue by JingGuo1997** [gao-lab/GLUE#94]
Hello to the developers of scGlue,

This is an excellent integration tool, and it has shown excellent consistency in my data. Additionally, I have some questions: for scRNA and scATAC data that do not have assigned cell types, is it reasonable to perform integration first and then use the integrated data for clustering analysis to determine cell types? Because I noticed 'n_vars=0' in the 'combined' object. 

Sincerely looking forward to your response.

**Comment by Jeff1995** [comment]
Hi @JingGuo1997. Thanks for your interest in GLUE!

Sure this is one of the key use cases for integration models like GLUE. You can perform clustering analysis on the integrated cell embeddings for cell type annotation.

To avoid potential integration artefacts, you may check the followings :

1. Compute the [integration consistency score](https://scglue.readthedocs.io/en/latest/training.html#Check-integration-diagnostics);
2. Compare with clustering results on single modalities;
3. Verify the annotation with marker gene expression/accessibility.

Let me know if there were further problems!
