### ISSUE TITLE
Error in guidance = scglue.genomics.rna_anchored_guidance_graph(rna, atac)

### ISSUE THREAD

**Issue by Wang-xin-rui** [gao-lab/GLUE#97]
Hi, sorry to bother you. When I run guidance = scglue.genomics.rna_anchored_guidance_graph(rna, atac), I got this error as follow:
![image](https://github.com/gao-lab/GLUE/assets/100898716/6a188d06-8593-4a9e-bced-a42a3439d04f)
pycharm The solution given is to install bedtoolds version 2.29.2 and above, but I have installed bedtools version 2.29.2.

**Comment by Jeff1995** [comment]
Hi @Wang-xin-rui, thanks for your interest in GLUE! Please refer to #22 and see if the discussions there were useful.
